# Funding options for ILAL Protocol

# GitHub Sponsors
# github: [your-username]

# Open Collective
# open_collective: ilal

# Patreon
# patreon: ilal

# Custom funding links
custom:
  - "Email: 2867755637@qq.com for partnership inquiries"
  - "Bug Bounty: docs/outreach/BUG_BOUNTY.md"
